"""create psps and vpas tables

Revision ID: 394e721a62c8
Revises: 5bb369de92a4
Create Date: 2026-07-29 16:52:48.447955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394e721a62c8'
down_revision: Union[str, Sequence[str], None] = '5bb369de92a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('psps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psps_code'), ['code'], unique=True)

    op.create_table('vpas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('psp_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['psp_id'], ['psps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vpas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vpas_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vpas_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_vpas_psp_id'), ['psp_id'], unique=False)
        batch_op.create_index('uq_vpas_primary_per_account', ['account_id'], unique=True, sqlite_where=sa.text('is_primary = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vpas', schema=None) as batch_op:
        batch_op.drop_index('uq_vpas_primary_per_account', sqlite_where=sa.text('is_primary = 1'))
        batch_op.drop_index(batch_op.f('ix_vpas_psp_id'))
        batch_op.drop_index(batch_op.f('ix_vpas_address'))
        batch_op.drop_index(batch_op.f('ix_vpas_account_id'))

    op.drop_table('vpas')
    with op.batch_alter_table('psps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psps_code'))

    op.drop_table('psps')
    # ### end Alembic commands ###
