"""create payment_events and notifications tables

Revision ID: 7538ce13c7e6
Revises: c09bd6150c4e
Create Date: 2026-07-31 15:58:59.345409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7538ce13c7e6'
down_revision: Union[str, Sequence[str], None] = 'c09bd6150c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', name='notificationchannel', native_enum=False, length=10), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='notificationstatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('INITIATED', 'PROCESSING', 'DEBITED', 'CREDITED', 'SUCCESS', 'FAILED', name='paymenteventtype', native_enum=False, length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_events_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_created_at'))

    op.drop_table('payment_events')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_payment_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
