"""create payments and idempotency_keys tables, add payment_id to ledger_entries

Revision ID: c09bd6150c4e
Revises: 45a72aedbee3
Create Date: 2026-07-30 20:01:45.419336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09bd6150c4e'
down_revision: Union[str, Sequence[str], None] = '45a72aedbee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='idempotencystatus', native_enum=False, length=20), nullable=False),
    sa.Column('response_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_account_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_account_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_psp_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PROCESSING', 'SUCCESS', 'FAILED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by_psp_id'], ['psps.id'], ),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_receiver_account_id'), ['receiver_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sender_account_id'), ['sender_account_id'], unique=False)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ledger_entries_payment_id'), ['payment_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_ledger_entries_payment_id_payments", "payments", ["payment_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ledger_entries_payment_id_payments", type_="foreignkey")
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payment_id'))
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_sender_account_id'))
        batch_op.drop_index(batch_op.f('ix_payments_receiver_account_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))

    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
